# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  # nvidia bullshit:
  # hardware = {
  #   graphics = {
  #     enable = true;
  #     enable32Bit = true;
  #   };
  #   nvidia = {
  #     modesetting.enable = true;
  #     open = false;
  #     package = config.boot.kernelPackages.nvidiaPackages.stable;
  #     nvidiaSettings = true;
  #   };
  # };
  # services.xserver.videoDrivers = [ "nvidia" ];
  # boot.kernelParams = [ "nouveau.runpm=0" ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
