text = "#rrggbb"
black = ["#rrggbb", "meaning"]
b_black = ["#rrggbb", "meaning"]
red = ["#rrggbb", "meaning"]
b_red = ["#rrggbb", "meaning"]
green = ["#rrggbb", "meaning"]
b_green = ["#rrggbb", "meaning"]
yellow = ["#rrggbb", "meaning"]
b_yellow = ["#rrggbb", "meaning"]
blue = ["#rrggbb", "meaning"]
b_blue = ["#rrggbb", "meaning"]
magenta = ["#rrggbb", "meaning"]
b_magenta = ["#rrggbb", "meaning"]
cyan = ["#rrggbb", "meaning"]
b_cyan = ["#rrggbb", "meaning"]
white = ["#rrggbb", "meaning"]
b_white = ["#rrggbb", "meaning"]