
[main]
'1' = {keyd = "noop"}
'`' = {keyd = "noop"}
2 = ":"
3 = "="
4 = {keyd = "noop"} 
5 = {keyd = "noop"}
6 = {keyd = "noop"} 
7 = {keyd = "noop"}
8 = {keyd = "noop"}
9 = '?'
0 = "&"
"-" = {keyd = "noop"} 
"=" = {keyd = "noop"}
q = ['z', 'back']
w = 'y'
e = ['f', 'find'] 
r = 'p'
t = ";"
y = "'"
u = 'g'
i = ['c', 'copy']
o = ['r', 'reset']
p = ['l', 'close']
'[' = '/'
']' = '~'
'\' = '@' 
'/' = {layer = 'numbers'}
a = ['a', 'up']
s = ['o', 'left']
d = ['e', 'right']
f = ['u', 'down']
g = ['i', 'into']
h = ['d', 'inspect']
j = ['h', 'select']
k = ['t', 'new']
l = ['n', 'insert']
';' = ['s', 'delete']
"'" = '.'
z = { layer = 'programming' }
x = 'q' 
c = 'j'
v = 'k'
b = 'x'
n = 'b'
m = 'm'
',' = ['w', 'save']
'.' = 'v'

leftalt = {layer = 'meta' }
leftmeta = { layer = 'altgr' }
rightalt = { layer = 'alt' }
capslock = 'esc'

[modifier_aliases]
shift = "invert"
control = "aux"
meta = "window"
alt = "action"
altgr = "special"

[layer.numbers]
a = '0'
w = '1'
e = '2'
r = '3'
s = '4'
d = '5'
f = '6'
x = '7'
c = '8'
v = '9'
# redundancies:
t = '+'
g = '-'
capslock = '.'
q = '_'
1 = '*'
2 = '/'
3 = '%'
4 = '$'

[layer.programming]
j = '('
k = ')'
u = '{'
i = '}'
n = '['
m = ']'
o = '<'
l = '>'
y = '`'
'[' = '\'
s = '%'
d = '+'
f = '$'
t = '|'
g = '_'

[layer.shift--shift]
t = "_"
9 = "!"
0 = '*'
y = '"'
'[' = '#'
']' = '^'
'\' = 'capslock'
"'" = ','
